### ISSUE TITLE
Can't export transforms

### ISSUE THREAD

**Issue by LauraBreimann** [saalfeldlab/confocal-lens#1]
Hey @axtimwalde, 
thanks for writing this! I'm currently trying to correct the chromatic aberration in images with 5 channels and I'm following your video to get the lens correction models. 

Firstly I got one question: 
Do I have to capture 4x4 tile images of my beads to do the lens correction? I used a single image tile but wasn't able to select the "Lens correction" feature and I was wondering if that's because I didn't use image tiles? 

Second I got stuck at the step of exporting the transformations: 
I opened the scripting interpreter and typed what I could see in the video: 
`IJ.log(Display.getFront().getActive().getFullCoordinateTransform().toXML(""))`

but this didn't work: 

`Sourced file: inline evaluation of: ``IJ.log(Display.getFront().getActive().getFullCoordinateTransform().toXML(""));'' : Attempt to resolve method: getFront() on undefined variable or class name: Display : at Line: 1 : in file: inline evaluation of: ``IJ.log(Display.getFront().getActive().getFullCoordinateTransform().toXML(""));'' : Display .getFront ( ) ` 

Not sure what I was doing wrong? 
Thanks for your help!

Cheers, 
Laura

**Comment by axtimwalde** [comment]
3x3 could be enough, overlap >50%, 4x4 has some more redundancy. You must get rid of lens distortion before you can remove the remaining chromatic aberration by an affine transformation with this method. If all you want to do is to align color channels, you could also just do elastic layer alignment. Some unknown lens distortion would remain in that case, so not good for stitching. Regarding the import error, I'll get back tomorrow.

**Comment by axtimwalde** [comment]
The complete script for export is here: https://github.com/saalfeldlab/confocal-lens/blob/master/scripts/export-transforms.bsh
It has all the necessary imports to get this to work, or you just run it.

**Comment by LauraBreimann** [comment]
Perfect, thank you, that worked for me!
